name: Pull Request Stats

on:
  pull_request:
    types: [ opened ]
  schedule:
    - cron: '0 9 * * 1'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          organization: '010tech'
          period: 30
          charts: true
          sort-by: 'REVIEWS'
          slack-webhook: 'https://hooks.slack.com/services/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'
          slack-channel: '#code-review'